app:
  replicaCount: 3
  revisionHistoryLimit: 2
  image:
    repository: barsalo221/car-app
    tag: "v1.0.646"
    pullPolicy: Always
    containerPort: 5000

mongodb:
  image: mongo:latest
  initImage: busybox:latest
  port: 27017
  type: LoadBalancer
  replicaCount: 1
  storage:
    size: 1Gi
    storageClass: db-storage
    path: /data/db
    bindingMode: WaitForFirstConsumer

service:
  port: 80
  targetPort: 5000
  nodePort: 30001