apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-car-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: car-container
        image: car-web-app3.0
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        env:
          - name: MONGO_URI
            valueFrom:        
              secretKeyRef:
                name: car-app-secret # השם של ה-Secret מקובץ הקודם
                key: MONGO_URI       # המפתח הספציפי שאנחנו רוצים לשלוף