# בקשה לשטח אחסון (PVC)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  storageClassName: db-storage # חיבור ל-SC
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi 

---
# Deployment של מונגו
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongo
          image: mongo:7.0
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db # זה המיקום שבו מונגו שומר נתונים בתוך הקונטיינר
      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: mongo-pvc 