apiVersion: v1
kind: Service
metadata:
  name: mongo-svc # זה השם שה-Flask יחפש!
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017      # הפורט שה-Service יחשוף
      targetPort: 27017 # הפורט שעליו מונגו רץ בתוך הפוד