apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "car-app.fullname" . }}  
  labels: {{- include "car-app.labels" . | nindent 4 }}
spec:
  revisionHistoryLimit: {{ .Values.app.revisionHistoryLimit }}
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      {{- include "car-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "car-app.selectorLabels" . | nindent 8 }}
    spec:
      readinessProbe:
        httpGet:
          path: /
          port: {{ .Values.app.image.containerPort }}
        initialDelaySeconds: 5
        periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.app.image.containerPort }}
          initialDelaySeconds: 10
          periodSeconds: 10
      containers:
        - name: car-container
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.app.image.containerPort }}
          env:
            - name: MONGO_URI
              value: "mongodb://{{ include "car-app.fullname" . }}-mongo-svc:27017/car_db"
