apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "car-app.fullname" . }}  
  labels: {{- include "car-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      {{- include "car-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "car-app.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: car-container
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.app.image.containerPort }}
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: car-app-secret
                  key: MONGO_URI
