apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: {{ include "car-app.fullname" . }}-ingress
    annotations:
        kubernetes.io/ingress.class: traefik
spec:
    rules:
        - host: car-app.local
        http:
            paths:
                - path: /
                pathType: Prefix
                backend:
                    service:
                        name: {{ include "car-app.fullname" . }}-svc
                        port:
                            number: 5000