apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "car-app.fullname" . }}-ingress
  labels: {{- include "car-app.labels" . | nindent 4 }}
  namespace: default
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/service.sticky.cookie: "true"
    traefik.ingress.kubernetes.io/service.sticky.cookie.name: "sticky-cookie"
spec:
  ingressClassName: traefik
  rules:
  - host: car-app.local
    http:
      paths:
       - backend:
        servicename: {{ include "car-app.fullname" . }}-svc
        servicePort: 80
