apiVersion: networking.k8s.io/v1
kind: ingress
metadata:
  name: {{ include "car-app.fullname" . }}-ingress
  labels: {{- include "car-app.labels" . | nindent 4 }}
spec:
  rules:
    - host: car-app.local
      http:
        paths:
          path: /
          pathType: Prefix
          backend:
            service:
              name: {{ include "car-app.fullname" . }}-svc
              port:
                number: {{ .Values.service.port }}
---