apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "car-app.fullname" . }}-ingress
  labels: {{- include "car-app.labels" . | nindent 4 }}
  namespace: default
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`car-app.local`)
    kind: Rule
    services:
    - name: {{ include "car-app.fullname" . }}-svc
      port: 80