apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
    name: sticky
    namespace: default
spec:
    sticky:
        cookie:
            name: car_sticky
            httpOnly: true
            secure: false
            sameSite: lax