apiVersion: v1
kind: Service
metadata: 
  name: {{ include "car-app.fullname" . }}-mongo-svc
  labels: {{- include "car-app.labels" . | nindent 4 }}
spec:
  selector: 
    {{- include "car-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
