# PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.mongodb.storage.storageClass }}
  resources:
    requests:
      storage: {{ .Values.mongodb.storage.size }}
---
# MONGO Deployment
apiVersion: apps/v1kubectl delete -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: {{ .Values.mongodb.image }}
          ports:
            - containerPort: {{ .Values.mongodb.port }}
          volumeMounts:
            - name: mongo-storage
              mountPath: {{ .Values.mongodb.storage.path }}
      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: mongo-pvc
