apiVersion: v1
kind: Service
metadata:
  name: mongo-svc
spec:
  selector:
    type: {{ .Values.mongodb.type }}
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
