# PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.mongodb.storage.storageClass }}
  resources:
    requests:
      storage: {{ .Values.mongodb.storage.size }}
---
# MONGO Deployment
apiVersion: apps/v1
kind: Deployment
metadata:   
  name: {{ include "car-app.fullname" . }}-mongo-deploy
  labels: {{- include "car-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.mongodb.replicaCount }}
  selector:
    matchLabels: 
    {{- include "car-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: 
      {{- include "car-app.selectorLabels" . | nindent 8 }}
    spec:
      initContainers:
        - name: fix-permissions
          image: {{ .Values.mongodb.initImage }}
          command: ["sh", "-c", "chown -R 999:999 /data/db"]
          volumeMounts:
            - name: mongo-storage
              mountPath: {{ .Values.mongodb.storage.path }}
      containers:
        - name: mongodb
          image: {{ .Values.mongodb.image }}
          ports:
            - containerPort: {{ .Values.mongodb.port }}
      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: mongo-pvc
