apiVersion: v1
kind: Service
metadata:
  name: {{ include "car-app.fullname" . }}-svc
  labels: {{- include "car-app.labels" . | nindent 4 }}
  annotations:
    traefik.ingress.kubernetes.io/service.sticky.cookie: "true"
    traefik.ingress.kubernetes.io/service.sticky.cookie.name: "sticky-cookie"

spec:
  selector:
    {{- include "car-app.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      # nodePort: {{ .Values.service.nodePort }}
